const data = {
  hits: [
    {
      created_at: "2020-07-22T14:44:27.000Z",
      title:
        "First Ever Image of a Multi-Planet System Around a Sun-Like Star Captured by ESO",
      url: "https://www.eso.org/public/news/eso2011/?lang",
      author: "rbanffy",
      points: 584,
      story_text: null,
      comment_text: null,
      num_comments: 15,
      story_id: null,
      story_title: null,
      sno: 1,
      story_url: null,
      parent_id: null,
      created_at_i: 1595429067,
      _tags: ["story", "author_rbanffy", "story_23917559", "front_page"],
      objectID: "23917559",
      _highlightResult: {
        title: {
          value:
            "First Ever Image of a Multi-Planet System Around a Sun-Like Star Captured by ESO",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://www.eso.org/public/news/eso2011/?lang",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "rbanffy", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-22T14:26:44.000Z",
      title: "Fawkes: Image “Cloaking” for Personal Privacy",
      url: "http://sandlab.cs.uchicago.edu/fawkes/",
      author: "MindGods",
      points: 39,
      story_text: null,
      comment_text: null,
      sno: 2,

      num_comments: 17,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595428004,
      _tags: ["story", "author_MindGods", "story_23917337", "front_page"],
      objectID: "23917337",
      _highlightResult: {
        title: {
          value: "Fawkes: Image “Cloaking” for Personal Privacy",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "http://sandlab.cs.uchicago.edu/fawkes/",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "MindGods", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-22T23:37:09.000Z",
      title:
        "Breach exposed more than one million DNA profiles on a major genealogy database",
      url:
        "https://www.buzzfeednews.com/article/peteraldhous/hackers-gedmatch-dna-privacy",
      author: "pseudolus",
      points: 37,
      story_text: null,
      comment_text: null,
      num_comments: 171,
      sno: 3,

      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595461029,
      _tags: ["story", "author_pseudolus", "story_23922733", "front_page"],
      objectID: "23922733",
      _highlightResult: {
        title: {
          value:
            "Breach exposed more than one million DNA profiles on a major genealogy database",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value:
            "https://www.buzzfeednews.com/article/peteraldhous/hackers-gedmatch-dna-privacy",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "pseudolus", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-22T17:09:49.000Z",
      title: "Apple Security Research Device Program",
      url: "https://developer.apple.com/programs/security-research-device/",
      author: "dewey",
      points: 294,
      story_text: null,
      comment_text: null,
      sno: 4,

      num_comments: 157,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595437789,
      _tags: ["story", "author_dewey", "story_23919175", "front_page"],
      objectID: "23919175",
      _highlightResult: {
        title: {
          value: "Apple Security Research Device Program",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value:
            "https://developer.apple.com/programs/security-research-device/",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "dewey", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-22T20:03:53.000Z",
      title:
        "Show HN: MineSweeper implemented in 100% CSS and HTML – no JavaScript",
      url: "https://github.com/propjockey/css-sweeper#readme",
      author: "James0x57",
      points: 288,
      story_text: null,
      sno: 5,

      comment_text: null,
      num_comments: 67,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595448233,
      _tags: [
        "story",
        "author_James0x57",
        "story_23920987",
        "show_hn",
        "front_page",
      ],
      objectID: "23920987",
      _highlightResult: {
        title: {
          value:
            "Show HN: MineSweeper implemented in 100% CSS and HTML – no JavaScript",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://github.com/propjockey/css-sweeper#readme",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "James0x57", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-22T21:09:11.000Z",
      title: "Amazon Ion",
      url: "https://amzn.github.io/ion-docs/",
      author: "BerislavLopac",
      points: 230,
      story_text: null,
      comment_text: null,
      sno: 6,

      num_comments: 86,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595452151,
      _tags: ["story", "author_BerislavLopac", "story_23921610", "front_page"],
      objectID: "23921610",
      _highlightResult: {
        title: { value: "Amazon Ion", matchLevel: "none", matchedWords: [] },
        url: {
          value: "https://amzn.github.io/ion-docs/",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "BerislavLopac",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-23T00:22:05.000Z",
      title:
        "The personal info of what could be Instacart customers is being sold online",
      url:
        "https://www.buzzfeednews.com/article/janelytvynenko/instacart-customers-info-sold-online",
      author: "coloneltcb",
      points: 199,
      story_text: null,
      sno: 7,

      comment_text: null,
      num_comments: 45,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595463725,
      _tags: ["story", "author_coloneltcb", "story_23922961", "front_page"],
      objectID: "23922961",
      _highlightResult: {
        title: {
          value:
            "The personal info of what could be Instacart customers is being sold online",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value:
            "https://www.buzzfeednews.com/article/janelytvynenko/instacart-customers-info-sold-online",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "coloneltcb", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-22T18:10:58.000Z",
      title: "Mathematicians discover a perfect way to multiply (2019)",
      url:
        "https://www.quantamagazine.org/mathematicians-discover-the-perfect-way-to-multiply-20190411/",
      author: "mmphosis",
      points: 185,
      story_text: null,
      comment_text: null,
      num_comments: 75,
      story_id: null,
      story_title: null,
      story_url: null,
      sno: 8,

      parent_id: null,
      created_at_i: 1595441458,
      _tags: ["story", "author_mmphosis", "story_23919869", "front_page"],
      objectID: "23919869",
      _highlightResult: {
        title: {
          value: "Mathematicians discover a perfect way to multiply (2019)",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value:
            "https://www.quantamagazine.org/mathematicians-discover-the-perfect-way-to-multiply-20190411/",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "mmphosis", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-21T19:23:31.000Z",
      title: "Is every game of Slay the Spire winnable?",
      url: "https://forgottenarbiter.github.io/Is-Every-Seed-Winnable/",
      author: "jsnell",
      points: 182,
      story_text: null,
      comment_text: null,
      num_comments: 126,
      story_id: null,
      story_title: null,
      sno: 9,

      story_url: null,
      parent_id: null,
      created_at_i: 1595359411,
      _tags: ["story", "author_jsnell", "story_23910006", "front_page"],
      objectID: "23910006",
      _highlightResult: {
        title: {
          value: "Is every game of Slay the Spire winnable?",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://forgottenarbiter.github.io/Is-Every-Seed-Winnable/",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "jsnell", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-22T17:39:04.000Z",
      title: "A React implementation of Spectrum, Adobe’s design system",
      url: "https://react-spectrum.adobe.com/react-spectrum/",
      author: "tga",
      points: 181,
      story_text: null,
      sno: 10,

      comment_text: null,
      num_comments: 52,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595439544,
      _tags: ["story", "author_tga", "story_23919509", "front_page"],
      objectID: "23919509",
      _highlightResult: {
        title: {
          value: "A React implementation of Spectrum, Adobe’s design system",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://react-spectrum.adobe.com/react-spectrum/",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "tga", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-22T20:56:10.000Z",
      title: "Show HN: React Guitar – A guitar component for React",
      url: "https://react-guitar.com",
      author: "4lejandrito",
      points: 170,
      story_text: null,
      comment_text: null,
      num_comments: 30,
      story_id: null,
      story_title: null,
      story_url: null,
      sno: 11,

      parent_id: null,
      created_at_i: 1595451370,
      _tags: [
        "story",
        "author_4lejandrito",
        "story_23921478",
        "show_hn",
        "front_page",
      ],
      objectID: "23921478",
      _highlightResult: {
        title: {
          value: "Show HN: React Guitar – A guitar component for React",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://react-guitar.com",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "4lejandrito", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-22T17:20:52.000Z",
      title: "Semgrep: Lightweight static analysis for many languages",
      url: "https://github.com/returntocorp/semgrep",
      author: "kiyanwang",
      points: 165,
      story_text: null,
      comment_text: null,
      num_comments: 20,
      sno: 1992,

      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595438452,
      _tags: ["story", "author_kiyanwang", "story_23919313", "front_page"],
      objectID: "23919313",
      _highlightResult: {
        title: {
          value: "Semgrep: Lightweight static analysis for many languages",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://github.com/returntocorp/semgrep",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "kiyanwang", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-23T00:00:11.000Z",
      title: "macOS 11 Virtualization Framework to Run Linux in a VM",
      url: "https://developer.apple.com/documentation/virtualization",
      author: "_venkatasg",
      points: 130,
      story_text: null,
      comment_text: null,
      num_comments: 98,
      story_id: null,
      story_title: null,
      story_url: null,
      sno: 162,

      parent_id: null,
      created_at_i: 1595462411,
      _tags: ["story", "author__venkatasg", "story_23922846", "front_page"],
      objectID: "23922846",
      _highlightResult: {
        title: {
          value: "macOS 11 Virtualization Framework to Run Linux in a VM",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://developer.apple.com/documentation/virtualization",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "_venkatasg", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-20T22:02:50.000Z",
      title: "New Data on T Cells and the Coronavirus",
      url:
        "https://blogs.sciencemag.org/pipeline/archives/2020/07/15/new-data-on-t-cells-and-the-coronavirus",
      author: "walterbell",
      points: 92,
      story_text: null,
      comment_text: null,
      num_comments: 42,
      story_id: null,
      story_title: null,
      sno: 122,

      story_url: null,
      parent_id: null,
      created_at_i: 1595282570,
      _tags: ["story", "author_walterbell", "story_23902361", "front_page"],
      objectID: "23902361",
      _highlightResult: {
        title: {
          value: "New Data on T Cells and the Coronavirus",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value:
            "https://blogs.sciencemag.org/pipeline/archives/2020/07/15/new-data-on-t-cells-and-the-coronavirus",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "walterbell", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-22T15:20:54.000Z",
      title:
        "Launch HN: Reploy (YC S20) – Instant fullstack staging environments for web apps",
      url: null,
      author: "podoman",
      points: 91,
      story_text:
        'Hello Hacker News! We\u0026#x27;re Jay and Himank from Reploy (\u003ca href="https:\u0026#x2F;\u0026#x2F;getreploy.com" rel="nofollow"\u003ehttps:\u0026#x2F;\u0026#x2F;getreploy.com\u003c/a\u003e). We\u0026#x27;re building a platform that allows teams to easily configure full-stack staging environments or \u0026quot;previews\u0026quot; of their web app which are created on every open PR.\u003cp\u003eIn the past, Himank and I spent time at several startups (~10-\u0026gt;200 employees), where we were on customer-facing, product-oriented teams. We often found ourselves in positions where we wanted to share our environment with designer\u0026#x2F;PM\u0026#x2F;sales folks who didn\u0026#x27;t necessarily have a dev environment setup, and ngrok didn\u0026#x27;t cut it.  Further, even when trying to share our environment with fellow engineers, there was always a slow down when requiring that they git stash, git pull, etc..\u003cp\u003eThe solution to these pain points was either:\u003cp\u003e1) Waiting for a full staging or production deployment, which in most cases, wasn\u0026#x27;t really practical (from a cost and\u0026#x2F;or time perspective).\u003cp\u003e2) Using a static site hosting solution (Vercel, Netlify, etc..) which didn\u0026#x27;t allow us to preview full-stack changes.\u003cp\u003eAt some of these companies, an infra team had tried to build something like this, however, the \u0026quot;preview\u0026quot; workflow was very different than the \u0026quot;production\u0026quot; workflow, so there were annoyances (slow builds, lack of concurrent env support, no populating staging data etc..) that made the tool hard to use. This is where Reploy comes in! Especially in the current remote landscape, being able to have as many staging environments as features is helping teams move faster by simplifying and streamlining the feature development flow.\u003cp\u003eWe\u0026#x27;ve put a lot of time into making this dead simple to set up. Just connect your repo, give us the commands that you run on your dev machine, and we\u0026#x27;ll spit out a live environment on a managed link. All of this configuration can be described in the `reploy.yml` file, which is essentially a simpler version of docker-compose :). And if you already have a docker-compose file, we can use that as well :).\u003cp\u003eTake a look at a demo on our site! (\u003ca href="https:\u0026#x2F;\u0026#x2F;getreploy.com" rel="nofollow"\u003ehttps:\u0026#x2F;\u0026#x2F;getreploy.com\u003c/a\u003e).\u003cp\u003eHow does it work you may ask? The short answer is k8s. We schedule these environments on Kubernetes, however, we hide this from end-users so that all that they\u0026#x27;re interacting with is the Reploy configuration (just a series of commands to start up your web app). We\u0026#x27;ve also curated a bunch of \u0026quot;runtimes\u0026quot;  which contain common framework dependencies (reactjs, node, rails, etc..) so that if you don\u0026#x27;t want to worry about docker, you don\u0026#x27;t have to :) . And for the hardcore folks out there, we also support custom images.\u003cp\u003eA few notable features that Reploy offers (specific to the aforementioned \u0026quot;staging\u0026quot; workflow):\u003cp\u003e1) Caching of specific directories (node_modules, .bundle, etc..) -\u0026gt; faster builds\u003cp\u003e2) Restarts of past environments -\u0026gt; Let\u0026#x27;s you compare the state of different commits\u003cp\u003e3) Notifications! -\u0026gt; We\u0026#x27;ll notify your team when a new environment is ready or failed the build process via slack, email, etc..\u003cp\u003e4) A \u0026quot;setup\u0026quot; hook where your team can populate a database with staging data, or configure the host environment to your liking.\u003cp\u003eFrom a pricing angle, we\u0026#x27;re looking to charge like most CI providers. That is, we\u0026#x27;ll charge a base price per engineer\u0026#x2F;user (~$30) and prorate any additional usage over a max number of concurrent environments. On that note, we\u0026#x27;ve realized that pricing for Reploy is a very interesting problem, as the types of users that are creating environments (engineers, devops teams, etc..) are not necessarily the only users getting value out of the product (PMs, for example). If you have any thoughts here, we\u0026#x27;d love to hear them in the comments!\u003cp\u003eFeel free to request access at \u003ca href="https:\u0026#x2F;\u0026#x2F;getreploy.com" rel="nofollow"\u003ehttps:\u0026#x2F;\u0026#x2F;getreploy.com\u003c/a\u003e if you\u0026#x27;re interested in getting up and running; also happy to answer any questions at `jay [at] getreploy.com`.\u003cp\u003eOverall, very excited to be sharing this with HN, we\u0026#x27;d love to hear your thoughts and keep the conversation going :).',
      comment_text: null,
      num_comments: 73,
      story_id: null,
      story_title: null,
      story_url: null,
      sno: 2,

      parent_id: null,
      created_at_i: 1595431254,
      _tags: ["story", "author_podoman", "story_23917956", "front_page"],
      objectID: "23917956",
      _highlightResult: {
        title: {
          value:
            "Launch HN: Reploy (YC S20) – Instant fullstack staging environments for web apps",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "podoman", matchLevel: "none", matchedWords: [] },
        story_text: {
          value:
            "Hello Hacker News! We're Jay and Himank from Reploy (\u003ca href=\"https://getreploy.com\" rel=\"nofollow\"\u003ehttps://getreploy.com\u003c/a\u003e). We're building a platform that allows teams to easily configure full-stack staging environments or \u0026quot;previews\u0026quot; of their web app which are created on every open PR.\u003cp\u003eIn the past, Himank and I spent time at several startups (~10-\u0026gt;200 employees), where we were on customer-facing, product-oriented teams. We often found ourselves in positions where we wanted to share our environment with designer/PM/sales folks who didn't necessarily have a dev environment setup, and ngrok didn't cut it.  Further, even when trying to share our environment with fellow engineers, there was always a slow down when requiring that they git stash, git pull, etc..\u003cp\u003eThe solution to these pain points was either:\u003cp\u003e1) Waiting for a full staging or production deployment, which in most cases, wasn't really practical (from a cost and/or time perspective).\u003cp\u003e2) Using a static site hosting solution (Vercel, Netlify, etc..) which didn't allow us to preview full-stack changes.\u003cp\u003eAt some of these companies, an infra team had tried to build something like this, however, the \u0026quot;preview\u0026quot; workflow was very different than the \u0026quot;production\u0026quot; workflow, so there were annoyances (slow builds, lack of concurrent env support, no populating staging data etc..) that made the tool hard to use. This is where Reploy comes in! Especially in the current remote landscape, being able to have as many staging environments as features is helping teams move faster by simplifying and streamlining the feature development flow.\u003cp\u003eWe've put a lot of time into making this dead simple to set up. Just connect your repo, give us the commands that you run on your dev machine, and we'll spit out a live environment on a managed link. All of this configuration can be described in the `reploy.yml` file, which is essentially a simpler version of docker-compose :). And if you already have a docker-compose file, we can use that as well :).\u003cp\u003eTake a look at a demo on our site! (\u003ca href=\"https://getreploy.com\" rel=\"nofollow\"\u003ehttps://getreploy.com\u003c/a\u003e).\u003cp\u003eHow does it work you may ask? The short answer is k8s. We schedule these environments on Kubernetes, however, we hide this from end-users so that all that they're interacting with is the Reploy configuration (just a series of commands to start up your web app). We've also curated a bunch of \u0026quot;runtimes\u0026quot;  which contain common framework dependencies (reactjs, node, rails, etc..) so that if you don't want to worry about docker, you don't have to :) . And for the hardcore folks out there, we also support custom images.\u003cp\u003eA few notable features that Reploy offers (specific to the aforementioned \u0026quot;staging\u0026quot; workflow):\u003cp\u003e1) Caching of specific directories (node_modules, .bundle, etc..) -\u0026gt; faster builds\u003cp\u003e2) Restarts of past environments -\u0026gt; Let's you compare the state of different commits\u003cp\u003e3) Notifications! -\u0026gt; We'll notify your team when a new environment is ready or failed the build process via slack, email, etc..\u003cp\u003e4) A \u0026quot;setup\u0026quot; hook where your team can populate a database with staging data, or configure the host environment to your liking.\u003cp\u003eFrom a pricing angle, we're looking to charge like most CI providers. That is, we'll charge a base price per engineer/user (~$30) and prorate any additional usage over a max number of concurrent environments. On that note, we've realized that pricing for Reploy is a very interesting problem, as the types of users that are creating environments (engineers, devops teams, etc..) are not necessarily the only users getting value out of the product (PMs, for example). If you have any thoughts here, we'd love to hear them in the comments!\u003cp\u003eFeel free to request access at \u003ca href=\"https://getreploy.com\" rel=\"nofollow\"\u003ehttps://getreploy.com\u003c/a\u003e if you're interested in getting up and running; also happy to answer any questions at `jay [at] getreploy.com`.\u003cp\u003eOverall, very excited to be sharing this with HN, we'd love to hear your thoughts and keep the conversation going :).",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T20:28:50.000Z",
      title: "Show HN: Biff – Self-hosted Firebase alternative for Clojure",
      url: "https://findka.com/biff/",
      author: "jacobobryant",
      points: 91,
      story_text: null,
      comment_text: null,
      num_comments: 18,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      sno: 1124,

      created_at_i: 1595449730,
      _tags: [
        "story",
        "author_jacobobryant",
        "story_23921220",
        "show_hn",
        "front_page",
      ],
      objectID: "23921220",
      _highlightResult: {
        title: {
          value: "Show HN: Biff – Self-hosted Firebase alternative for Clojure",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://findka.com/biff/",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "jacobobryant", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-23T01:43:00.000Z",
      title: "KDE Slimbook: Linux Laptop with Ryzen 4000",
      url: "https://kde.slimbook.es/",
      author: "ekianjo",
      points: 90,
      story_text: null,
      comment_text: null,
      num_comments: 54,
      story_id: null,
      story_title: null,
      sno: 113,

      story_url: null,
      parent_id: null,
      created_at_i: 1595468580,
      _tags: ["story", "author_ekianjo", "story_23923381", "front_page"],
      objectID: "23923381",
      _highlightResult: {
        title: {
          value: "KDE Slimbook: Linux Laptop with Ryzen 4000",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://kde.slimbook.es/",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "ekianjo", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-22T21:27:04.000Z",
      title: "New Features in Gnuplot 5.4",
      url: "https://lwn.net/SubscriberLink/826456/2ea90dd464e104d5/",
      author: "leephillips",
      points: 84,
      story_text: null,
      comment_text: null,
      num_comments: 14,
      story_id: null,
      story_title: null,
      story_url: null,
      sno: 1120,

      parent_id: null,
      created_at_i: 1595453224,
      _tags: ["story", "author_leephillips", "story_23921799", "front_page"],
      objectID: "23921799",
      _highlightResult: {
        title: {
          value: "New Features in Gnuplot 5.4",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://lwn.net/SubscriberLink/826456/2ea90dd464e104d5/",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "leephillips", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-22T22:16:41.000Z",
      title: "Flash Game History",
      url: "http://www.flashgamehistory.com/",
      author: "jslakro",
      points: 83,
      story_text: null,
      comment_text: null,
      sno: 66,

      num_comments: 31,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595456201,
      _tags: ["story", "author_jslakro", "story_23922206", "front_page"],
      objectID: "23922206",
      _highlightResult: {
        title: {
          value: "Flash Game History",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "http://www.flashgamehistory.com/",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "jslakro", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-23T03:06:06.000Z",
      title: "What is GPT-3? written in layman's terms",
      url: "https://tinkeredthinking.com/index.php?sno=841",
      author: "skylarker",
      points: 76,
      story_text: null,
      comment_text: null,
      num_comments: 27,
      sno: 92,

      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595473566,
      _tags: ["story", "author_skylarker", "story_23923799", "front_page"],
      objectID: "23923799",
      _highlightResult: {
        title: {
          value: "What is GPT-3? written in layman's terms",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://tinkeredthinking.com/index.php?sno=841",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "skylarker", matchLevel: "none", matchedWords: [] },
      },
    },
  ],
  nbHits: 30,
  page: 0,
  nbPages: 2,
  hitsPerPage: 20,
  exhaustiveNbHits: true,
  query: "",
  params:
    "advancedSyntax=true\u0026analytics=true\u0026analyticsTags=backend\u0026tags=front_page",
  processingTimeMS: 1,
};
export default data;
