const data = {
  hits: [
    {
      created_at: "2020-07-22T23:24:30.000Z",
      title: "Twilio exposes SDK, attackers inject it with malvertising code",
      url:
        "https://www.bleepingcomputer.com/news/security/twilio-exposes-sdk-attackers-inject-it-with-malvertising-code/",
      author: "praveenweb",
      points: 1,
      story_text: null,
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595460270,
      _tags: ["story", "author_praveenweb", "story_23922658"],
      objectID: "23922658",
      _highlightResult: {
        title: {
          value:
            "Twilio exposes SDK, attackers inject it with malvertising code",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value:
            "https://www.bleepingcomputer.com/news/security/twilio-exposes-sdk-attackers-inject-it-with-malvertising-code/",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "praveenweb",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T23:24:17.000Z",
      title: "Data Science and Machine Learning Primer",
      url: "https://elitedatascience.com/primer",
      author: "reedwolf",
      points: 4,
      story_text: null,
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595460257,
      _tags: ["story", "author_reedwolf", "story_23922656"],
      objectID: "23922656",
      _highlightResult: {
        title: {
          value: "Data Science and Machine Learning Primer",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://elitedatascience.com/primer",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "reedwolf",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T23:23:07.000Z",
      title:
        "The Most Comprehensive History of Watch Legend Swatch You’ll Ever Need",
      url: "https://www.highsnobiety.com/p/swatch-watches-history/",
      author: "omarchowdhury",
      points: 1,
      story_text: null,
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595460187,
      _tags: ["story", "author_omarchowdhury", "story_23922649"],
      objectID: "23922649",
      _highlightResult: {
        title: {
          value:
            "The Most Comprehensive History of Watch Legend Swatch You’ll Ever Need",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://www.highsnobiety.com/p/swatch-watches-history/",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "omarchowdhury",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T23:22:58.000Z",
      title: "Almost a quarter of Delhi may have had coronavirus, finds study",
      url:
        "https://www.theguardian.com/world/2020/jul/22/almost-quarter-of-delhi-may-have-developed-covid-19-antibodies-study-coronavirus",
      author: "bookofjoe",
      points: 6,
      story_text: null,
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595460178,
      _tags: ["story", "author_bookofjoe", "story_23922648"],
      objectID: "23922648",
      _highlightResult: {
        title: {
          value:
            "Almost a quarter of Delhi may have had coronavirus, finds study",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value:
            "https://www.theguardian.com/world/2020/jul/22/almost-quarter-of-delhi-may-have-developed-covid-19-antibodies-study-coronavirus",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "bookofjoe",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T23:20:19.000Z",
      title: "Ask HN: How has covid19 effected the consulting market?",
      url: null,
      author: "dualcore",
      points: 1,
      story_text:
        "We are roughly 3 months into this pandemic and wondering how the consulting market is going for you?\u003cp\u003eDid you loose clients?\nHave rates been effected?\nIs it hard to find new clients?\nHas the halt of incoming talent into the US helped or hurted your business?\nIs this a really bad time to enter the consulting world?",
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595460019,
      _tags: ["story", "author_dualcore", "story_23922632", "ask_hn"],
      objectID: "23922632",
      _highlightResult: {
        title: {
          value: "Ask HN: How has covid19 effected the consulting market?",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "dualcore",
          matchLevel: "none",
          matchedWords: [],
        },
        story_text: {
          value:
            "We are roughly 3 months into this pandemic and wondering how the consulting market is going for you?\u003cp\u003eDid you loose clients?\nHave rates been effected?\nIs it hard to find new clients?\nHas the halt of incoming talent into the US helped or hurted your business?\nIs this a really bad time to enter the consulting world?",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T23:19:51.000Z",
      title: "New York Times Reaches Deal to Acquire Serial Productions",
      url:
        "https://www.wsj.com/articles/new-york-times-reaches-deal-to-acquire-serial-productions-11595452716",
      author: "awaxman11",
      points: 2,
      story_text: null,
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595459991,
      _tags: ["story", "author_awaxman11", "story_23922625"],
      objectID: "23922625",
      _highlightResult: {
        title: {
          value: "New York Times Reaches Deal to Acquire Serial Productions",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value:
            "https://www.wsj.com/articles/new-york-times-reaches-deal-to-acquire-serial-productions-11595452716",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "awaxman11",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T23:18:23.000Z",
      title: "John Sculley on How Steve Jobs Got Fired from Apple",
      url: "https://www.youtube.com/watch?v=f8V4XhtQ4H8",
      author: "tosh",
      points: 1,
      story_text: null,
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595459903,
      _tags: ["story", "author_tosh", "story_23922618"],
      objectID: "23922618",
      _highlightResult: {
        title: {
          value: "John Sculley on How Steve Jobs Got Fired from Apple",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://www.youtube.com/watch?v=f8V4XhtQ4H8",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "tosh", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-22T23:17:33.000Z",
      title:
        "FBI: China’s Top Diplomat in America Covertly Recruits Scientists",
      url:
        "https://www.thedailybeast.com/fbi-chinas-top-diplomat-in-america-covertly-recruits-scientists",
      author: "ycombonator",
      points: 10,
      story_text: null,
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595459853,
      _tags: ["story", "author_ycombonator", "story_23922613"],
      objectID: "23922613",
      _highlightResult: {
        title: {
          value:
            "FBI: China’s Top Diplomat in America Covertly Recruits Scientists",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value:
            "https://www.thedailybeast.com/fbi-chinas-top-diplomat-in-america-covertly-recruits-scientists",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "ycombonator",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T23:16:55.000Z",
      title:
        "pd.sh: preserve intermediate outputs in a Linux terminal pipeline command",
      url: "https://github.com/ketancmaheshwari/pd",
      author: "ketanmaheshwari",
      points: 2,
      story_text: null,
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595459815,
      _tags: ["story", "author_ketanmaheshwari", "story_23922610"],
      objectID: "23922610",
      _highlightResult: {
        title: {
          value:
            "pd.sh: preserve intermediate outputs in a Linux terminal pipeline command",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://github.com/ketancmaheshwari/pd",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "ketanmaheshwari",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T23:13:55.000Z",
      title: "So *that's* how Breitbart is still making money",
      url:
        "https://branded.substack.com/p/so-thats-how-breitbart-is-still-making",
      author: "enraged_camel",
      points: 7,
      story_text: null,
      comment_text: null,
      num_comments: 2,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595459635,
      _tags: ["story", "author_enraged_camel", "story_23922583"],
      objectID: "23922583",
      _highlightResult: {
        title: {
          value: "So *that's* how Breitbart is still making money",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value:
            "https://branded.substack.com/p/so-thats-how-breitbart-is-still-making",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "enraged_camel",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T23:12:18.000Z",
      title: "Hermit Crab Vacancy Chain",
      url: "https://vimeo.com/117375257",
      author: "elliekelly",
      points: 1,
      story_text: null,
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595459538,
      _tags: ["story", "author_elliekelly", "story_23922574"],
      objectID: "23922574",
      _highlightResult: {
        title: {
          value: "Hermit Crab Vacancy Chain",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://vimeo.com/117375257",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "elliekelly",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T23:10:13.000Z",
      title:
        "The story of the Tank Man photo by its photographer, Jeff Widener",
      url: "http://www.jeffwidener.com/index.php?/stories/2016/09/tankman/",
      author: "js2",
      points: 2,
      story_text: null,
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595459413,
      _tags: ["story", "author_js2", "story_23922562"],
      objectID: "23922562",
      _highlightResult: {
        title: {
          value:
            "The story of the Tank Man photo by its photographer, Jeff Widener",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value:
            "http://www.jeffwidener.com/index.php?/stories/2016/09/tankman/",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "js2", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-22T23:06:05.000Z",
      title: "MSFT: Progress on our goal to be carbon negative by 2030",
      url:
        "https://blogs.microsoft.com/on-the-issues/2020/07/21/carbon-negative-transform-to-net-zero/",
      author: "sirteno",
      points: 2,
      story_text: null,
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595459165,
      _tags: ["story", "author_sirteno", "story_23922529"],
      objectID: "23922529",
      _highlightResult: {
        title: {
          value: "MSFT: Progress on our goal to be carbon negative by 2030",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value:
            "https://blogs.microsoft.com/on-the-issues/2020/07/21/carbon-negative-transform-to-net-zero/",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "sirteno",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T23:05:25.000Z",
      title: "Frustrated by Formik? Here's a simpler way to do forms in React",
      url:
        "https://maxrozen.com/2020/07/23/frustrated-formik-simpler-react-forms/",
      author: "rozenmd",
      points: 2,
      story_text: null,
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595459125,
      _tags: ["story", "author_rozenmd", "story_23922527"],
      objectID: "23922527",
      _highlightResult: {
        title: {
          value:
            "Frustrated by Formik? Here's a simpler way to do forms in React",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value:
            "https://maxrozen.com/2020/07/23/frustrated-formik-simpler-react-forms/",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "rozenmd",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T23:04:39.000Z",
      title: "List of biggest companies by market cap",
      url:
        "https://www.tradingview.com/markets/stocks-usa/market-movers-large-cap/",
      author: "apsec112",
      points: 2,
      story_text: null,
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595459079,
      _tags: ["story", "author_apsec112", "story_23922517"],
      objectID: "23922517",
      _highlightResult: {
        title: {
          value: "List of biggest companies by market cap",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value:
            "https://www.tradingview.com/markets/stocks-usa/market-movers-large-cap/",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "apsec112",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T23:03:56.000Z",
      title: "Oral History of John Backus (2006)",
      url: "https://www.youtube.com/watch?v=dDsWTyLEgbk",
      author: "tosh",
      points: 4,
      story_text: null,
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595459036,
      _tags: ["story", "author_tosh", "story_23922509"],
      objectID: "23922509",
      _highlightResult: {
        title: {
          value: "Oral History of John Backus (2006)",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://www.youtube.com/watch?v=dDsWTyLEgbk",
          matchLevel: "none",
          matchedWords: [],
        },
        author: { value: "tosh", matchLevel: "none", matchedWords: [] },
      },
    },
    {
      created_at: "2020-07-22T23:00:44.000Z",
      title: "I’m scared for my future, what do I do?",
      url: "https://www.calmmindpower.com/post/scared-for-my-future",
      author: "morchelos",
      points: 1,
      story_text: null,
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595458844,
      _tags: ["story", "author_morchelos", "story_23922492"],
      objectID: "23922492",
      _highlightResult: {
        title: {
          value: "I’m scared for my future, what do I do?",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://www.calmmindpower.com/post/scared-for-my-future",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "morchelos",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T23:00:05.000Z",
      title:
        "Show HN: Blazing fast open-source autograder for coding problems (Django)",
      url: "https://github.com/arthtyagi/judge",
      author: "arthtyagi",
      points: 2,
      story_text: null,
      comment_text: null,
      num_comments: 1,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595458805,
      _tags: ["story", "author_arthtyagi", "story_23922488", "show_hn"],
      objectID: "23922488",
      _highlightResult: {
        title: {
          value:
            "Show HN: Blazing fast open-source autograder for coding problems (Django)",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value: "https://github.com/arthtyagi/judge",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "arthtyagi",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T22:59:22.000Z",
      title: "401(k) Plans No Longer Make Much Sense for Savers",
      url:
        "https://www.bloomberg.com/opinion/articles/2020-07-21/401-k-plans-no-longer-make-much-sense-for-savers",
      author: "JumpCrisscross",
      points: 3,
      story_text: null,
      comment_text: null,
      num_comments: 1,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595458762,
      _tags: ["story", "author_JumpCrisscross", "story_23922485"],
      objectID: "23922485",
      _highlightResult: {
        title: {
          value: "401(k) Plans No Longer Make Much Sense for Savers",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value:
            "https://www.bloomberg.com/opinion/articles/2020-07-21/401-k-plans-no-longer-make-much-sense-for-savers",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "JumpCrisscross",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
    {
      created_at: "2020-07-22T22:57:33.000Z",
      title:
        "How the World Passed a Carbon Threshold and Why It Matters (2017)",
      url:
        "https://e360.yale.edu/features/how-the-world-passed-a-carbon-threshold-400ppm-and-why-it-matters",
      author: "simonebrunozzi",
      points: 1,
      story_text: null,
      comment_text: null,
      num_comments: 0,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1595458653,
      _tags: ["story", "author_simonebrunozzi", "story_23922471"],
      objectID: "23922471",
      _highlightResult: {
        title: {
          value:
            "How the World Passed a Carbon Threshold and Why It Matters (2017)",
          matchLevel: "none",
          matchedWords: [],
        },
        url: {
          value:
            "https://e360.yale.edu/features/how-the-world-passed-a-carbon-threshold-400ppm-and-why-it-matters",
          matchLevel: "none",
          matchedWords: [],
        },
        author: {
          value: "simonebrunozzi",
          matchLevel: "none",
          matchedWords: [],
        },
      },
    },
  ],
  nbHits: 2097727,
  page: 10,
  nbPages: 50,
  hitsPerPage: 20,
  exhaustiveNbHits: false,
  query: "",
  params:
    "advancedSyntax=true\u0026analytics=true\u0026analyticsTags=backend\u0026page=10\u0026tags=story",
  processingTimeMS: 2,
};

export default data;
